#!/usr/bin/env sh
usage() {
    echo "usage: git vip <subcommand>"
    echo
    echo "Available subcommands are:"
}

version() {
    echo "git vip plugin v0.0.1-dev"
    echo
}
clone(){
	git svn clone -r HEAD $1;
	cd $2;
	git checkout -b svn
	git branch -D master
	git svn rebase
	git remote add origin $3
	git fetch --all
	git checkout -b master origin/master

}
main() {
    if [ "$#" -lt 1 ]; then
        usage; exit 1
    fi

    local subcommand="$1"; shift

    case $subcommand in
        "-h"|"--help")
            usage; exit 0
            ;;
        "-v"|"--version")
            version; exit 0
            ;;
    esac

    local workingdir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
    if [ ! -e "$workingdir/git-adamcodes-$subcommand" ]; then
        usage; exit 1
    fi

    source "$workingdir/git-adamcodes-$subcommand"

    if [ ! type "cmd_$subcommand" ]; then
        usage; exit 1
    fi

    cmd_$subcommand "$@"
}

main "$@"