#!/usr/bin/env sh
usage() {
    echo "usage: git vip <subcommand>"
    echo
    echo "Available subcommands are:"
}

version() {
    echo "git vip plugin v0.0.1-dev"
    echo
}
main() {
    if [ "$#" -lt 1 ]; then
        usage; exit 1
    fi

    local subcommand="$1"; shift

    case $subcommand in
        "-h"|"--help")
            usage; exit 0
            ;;
        "-v"|"--version")
            version; exit 0
            ;;
    esac

    local workingdir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
    if [ ! -e "$workingdir/git-vip-$subcommand" ]; then
        usage; exit 1
    fi

    source "$workingdir/git-vip-$subcommand"

    if [ ! type "cmd_$subcommand" ]; then
        usage; exit 1
    fi

    cmd_$subcommand "$@"
}

main "$@"